version: '3.8'

services:
  # MongoDB database
  mongodb:
    image: mongo:7
    container_name: campus-mental-health-db
    restart: unless-stopped
    environment:
      MONGO_INITDB_ROOT_USERNAME: ${MONGO_USERNAME:-admin}
      MONGO_INITDB_ROOT_PASSWORD: ${MONGO_PASSWORD:-secure_password}
      MONGO_INITDB_DATABASE: campus-mental-health
    volumes:
      - mongodb_data:/data/db
      - ./mongo-init.js:/docker-entrypoint-initdb.d/mongo-init.js:ro
    ports:
      - "27017:27017"
    networks:
      - campus-network

  # Redis for session management and Socket.io scaling
  redis:
    image: redis:7-alpine
    container_name: campus-mental-health-redis
    restart: unless-stopped
    command: redis-server --requirepass ${REDIS_PASSWORD:-secure_redis_password}
    volumes:
      - redis_data:/data
    ports:
      - "6379:6379"
    networks:
      - campus-network

  # Main application
  app:
    build: .
    container_name: campus-mental-health-app
    restart: unless-stopped
    environment:
      NODE_ENV: production
      PORT: 5000
      MONGODB_URI: mongodb://${MONGO_USERNAME:-admin}:${MONGO_PASSWORD:-secure_password}@mongodb:27017/campus-mental-health?authSource=admin
      REDIS_URL: redis://:${REDIS_PASSWORD:-secure_redis_password}@redis:6379
      AUTH0_DOMAIN: ${AUTH0_DOMAIN}
      AUTH0_AUDIENCE: ${AUTH0_AUDIENCE}
      JWT_SECRET: ${JWT_SECRET}
      CLIENT_URL: ${CLIENT_URL:-http://localhost:3000}
    ports:
      - "5000:5000"
    depends_on:
      - mongodb
      - redis
    networks:
      - campus-network
    volumes:
      - ./server/.env:/app/server/.env:ro

  # Nginx reverse proxy (optional, for production)
  nginx:
    image: nginx:alpine
    container_name: campus-mental-health-nginx
    restart: unless-stopped
    ports:
      - "80:80"
      - "443:443"
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf:ro
      - ./ssl:/etc/nginx/ssl:ro
    depends_on:
      - app
    networks:
      - campus-network
    profiles:
      - production

volumes:
  mongodb_data:
    driver: local
  redis_data:
    driver: local

networks:
  campus-network:
    driver: bridge